# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  test_openapi:
    cmds:
      - go run github.com/getkin/kin-openapi/cmd/validate@latest swagger.json 

  gen:
    cmds:
      - go generate api/generate.go

  get_api:
    cmds:
      - rm -f swagger.json 
      # - wget https://dac-static.atlassian.com/cloud/confluence/openapi-v2.v3.json
      - wget https://raw.githubusercontent.com/photoprism/photoprism/develop/internal/api/swagger.json

  edit_build:
    cmds:
      - go build cmd/api_fmt/main.go 

  edit_api:
    deps: [edit_build]
    cmds:
      - rm -f confluence.json 
      - ./main

  dia:
    cmds:
      - task: get_api
      - task: edit_api
      - task: gen
      - go vet ./...
